name: run main script

on:
  schedule:
    - cron: '0 9 * * *'  # Rodar todos os dias às 6:20 (UTC-3)
  push:
    branches:
      - main  # Rodar também quando houver push na branch main (para testes)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run main script
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PORT: ${{secrets.PORT}}
        DATABASE: ${{secrets.DATABASE}}
      run: python extract_data.py